const sidebar = [
  {
    items: [{
      name: 'Trang chủ',
      routeName: 'Home',
      icon: 'icon-book-open',
      roles: ['super_admin', 'admin', 'developer', 'admin_mission'],
    },
    // {
    //   name: 'Trang chủ',
    //   routeName: "HomeInGame",
    //   isRequireCurrentWheel: true,
    //   icon: 'icon-book-open',
    //   roles: ["super_admin", "admin", "developer", "admin_mission"]
    // },
    {
      name: 'Thiết lập chung',
      routeName: 'EditWheel',
      isRequireCurrentWheel: true,
      icon: 'icon-settings',
      roles: ['super_admin', 'admin', 'developer', 'admin_mission'],
    },
    {
      name: 'Kho phần thưởng',
      routeName: 'AllItem',
      icon: 'icon-gift',
      isRequireCurrentWheel: true,
      isShowReward: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Thiết kế',
      routeName: 'DesignWheelV4',
      isRequireCurrentWheel: true,
      gameType: 'wheel',
      icon: 'icon-edit-1',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Thiết kế',
      routeName: 'DesignLatHinhBeta',
      isRequireCurrentWheel: true,
      gameType: 'flipcard',
      icon: 'icon-edit-1',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Thiết kế',
      routeName: 'DesignMatchingBeta',
      isRequireCurrentWheel: true,
      gameType: 'matching',
      icon: 'icon-edit-1',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    }, {
      name: 'Thiết kế',
      routeName: 'DesignFlyingGift',
      isRequireCurrentWheel: true,
      gameType: 'flying_gift',
      icon: 'icon-edit-1',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Thiết kế',
      routeName: 'DesignLiXiBeta',
      icon: 'icon-edit-1',
      isRequireCurrentWheel: true,
      gameType: 'li_xi',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    }, {
      name: 'Thiết kế',
      badge: 'NEW',
      routeName: 'NewDesign',
      isRequireCurrentWheel: true,
      icon: 'icon-edit-1',
      roles: ['super_admin', 'admin', 'designer', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Nhiệm vụ',
      routeName: 'Missions',
      icon: 'icon-winner icon',
      isRequireCurrentWheel: true,
      isHideWidthLevelStarter: true,
      isHideWithGameScheme: ['quick'],
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Phân quyền',
      routeName: 'AllShareLinks',
      icon: 'icon-link-1',
      isRequireCurrentWheel: true,
      isNotShowInShareLink: true,
      isHideWidthLevelStarter: true,
      roles: ['super_admin', 'admin', 'developer', 'egany'],
    },
    {
      name: 'Trúng thưởng',
      routeName: 'AllReward2',
      isRequireCurrentWheel: true,
      isShowReward: true,
      icon: 'icon-award1',
      roles: ['super_admin', 'admin', 'customer_supporter', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Báo cáo',
      routeName: 'Report',
      isRequireCurrentWheel: true,
      icon: 'icon-grid',
      roles: ['super_admin', 'admin', 'developer', 'admin_mission'],
    }, {
      name: 'Quản lý người chơi',
      routeName: 'ManagePlayers',
      isRequireCurrentWheel: true,
      isHideWithGameScheme: ['quick'],
      icon: 'icon-users',
      roles: ['super_admin', 'admin', 'developer', 'admin_mission'],
    },
    {
      name: 'Woay Page',
      routeName: 'LandingPage',
      isRequireCurrentWheel: true,
      icon: 'icon-layout',
      isRequireWoayPageChannel: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Woay Popup',
      routeName: 'WoayPopup',
      icon: 'icon-layout',
      isRequireCurrentWheel: true,
      notShowGameLixi: true,
      isRequireWoayPopupChannel: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    }, {
      name: 'Tích hợp Haravan',
      routeName: 'WoayHaravan',
      icon: 'icon-layout',
      isRequireCurrentWheel: true,
      isRequireWoayHaravan: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Tích hợp Sapo',
      routeName: 'WoaySapo',
      icon: 'icon-layout',
      isRequireCurrentWheel: true,
      isRequireWoaySapo: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Mã chơi',
      routeName: 'AllPlayCode2',
      icon: 'icon-ticket',
      isRequireLoginMethodPlayCode: true,
      isRequireCurrentWheel: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Mã trúng thưởng',
      routeName: 'AllCode',
      icon: 'icon-redeem',
      isRequireInventoryCode: true,
      isShowReward: true,
      isRequireCurrentWheel: true,
      roles: ['super_admin', 'admin', 'developer', 'egany', 'admin_mission'],
    },
    {
      name: 'Hana AI',
      routeName: 'HanaAI',
      icon: 'icon-robot',
      isRequireLoginMethodFacebook: true,
      isRequireCurrentWheel: true,
      isHideWidthLevelStarter: true,
      roles: ['super_admin', 'developer', 'admin_mission'],
    },
    {
      name: 'Tính năng ẩn',
      icon: 'icon-sliders-1',
      isRequireCurrentWheel: true,
      children: [{
        name: 'Manychat',
        routeName: 'Manychat',
        isRequireCurrentWheel: true,
        isRequireLoginMethodFacebook: true,
        roles: ['super_admin', 'developer', 'admin_mission'],
      },
      {
        name: 'Nhiệm vụ',
        routeName: 'Mission',
        isRequireCurrentWheel: true,
        roles: ['super_admin', 'developer', 'admin_mission'],
      },
      {
        name: 'Email template',
        routeName: 'MailTemplate',
        isRequireCurrentWheel: true,
        roles: ['super_admin', 'developer'],
      },
      {
        name: 'Lịch sử admin',
        routeName: 'History',
        isRequireCurrentWheel: true,
        roles: ['super_admin', 'developer'],
      },
      {
        name: 'Lịch sử player',
        routeName: 'HistoryPlayers',
        isRequireCurrentWheel: true,
        roles: ['super_admin', 'developer'],
      },
      {
        name: 'Tổng quan cũ',
        routeName: 'EditWheelV3',
        isRequireCurrentWheel: true,
        roles: ['super_admin'],
      },
      {
        name: 'Tổng quan Legacy',
        routeName: 'EditWheelOld',
        isRequireCurrentWheel: true,
        roles: ['super_admin'],
      },
      {
        name: 'Kho giao diện',
        routeName: 'WheelTheme',
        isRequireCurrentWheel: true,
        gameType: 'wheel',
        roles: ['super_admin'],
      },
      ],
    }],
  },
];

export default sidebar;
